Program 1

In [ ]:
import numpy as np
a=np.array([10,15,20,25])
print("Basic array:")
print(a)
b=np.zeros((3,3),dtype=int)
print("Array of zeros:")
print(b)
c=np.ones((3,3),dtype=int)
print("Array of ones:")
print(c)
r=np.random.random((3,3))
print("Random numbers in nd array:")
print(r)
d=np.array([[10,20,30],[40,50,60],[60,70,90]])
print("Choice array:")
print(d)
i=np.eye(3,dtype=int)
print("Imatrix in numpy:")
print(i)
e=np.arange(0,10,2)
print("Evenly spaced array:")
print(e)

Program 2

In [ ]:
import numpy as np
a=np.array([[20,40,50,60],
            [80,90,90,94]])
print("Dimensions of numpy array:")
print(a.ndim)
print("Shape of numpy array:")
print(a.shape)
print(a.size)

print("Reshaping a numpy  array:\n",a.reshape(4,2))
c=a.flatten()
print("Flattening a numpy array:")
print(c)
d=a.transpose()
print("Transpose of a numpy array:")
print(d)

Program 3

In [1]:
import numpy as np
array=np.array([100,200,300])
print("Array:",array)
expandarray=np.expand_dims(array,axis=0)
print("Expanded array(axis=0):\n",expandarray)
expandarray1=np.expand_dims(array,axis=1)
print("Expanded array(axis=1):\n",expandarray1)

Array: [100 200 300]
Expanded array(axis=0):
 [[100 200 300]]
Expanded array(axis=1):
 [[100]
 [200]
 [300]]


In [2]:
import numpy as np
array=np.array([[[[10,20,30,40]],
                [[50,60,70,80]],
                [[90,100,110,120]]]])
print("Original shape:",array.shape)
squeezedarray=np.squeeze(array)
print("Squeezedshape:",squeezedarray.shape)
print(squeezedarray)

Original shape: (1, 3, 1, 4)
Squeezedshape: (3, 4)
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [3]:
import numpy as np
array=np.array([[30,10,20],[50,40,60]])
sortedarray=np.sort(array,axis=0)
print("Sorted along axis0(columns):\n",sortedarray)
sortedarray=np.sort(array,axis=1)
print("Sorted along axis 1(rows):\n",sortedarray)

Sorted along axis0(columns):
 [[30 10 20]
 [50 40 60]]
Sorted along axis 1(rows):
 [[10 20 30]
 [40 50 60]]


Program 4

In [5]:
import numpy as np
array1d=np.array([10,20,30,40,50,60,70,80,90,100])
print("array1d[2:7]:",array1d[2:7])
print("array1d[:5]:",array1d[:5])
print("array1d[5:]:",array1d[5:])
print("array1d[::2]:",array1d[::2])
print("array1d[1::2]:",array1d[1::2])

array1d[2:7]: [30 40 50 60 70]
array1d[:5]: [10 20 30 40 50]
array1d[5:]: [ 60  70  80  90 100]
array1d[::2]: [10 30 50 70 90]
array1d[1::2]: [ 20  40  60  80 100]


In [9]:
import numpy as np
array2d=np.array([[5,10,15,20],
                  [25,30,35,40],
                  [45,50,55,60],
                  [65,70,75,80]])
print('array2d[1:3,1:3]:\n',array2d[1:3,1:3])
print('array2d[:2,:2]:\n',array2d[:2,:2])
print('array2d[2:,2:]:\n',array2d[2:,2:])

array2d[1:3,1:3]:
 [[30 35]
 [50 55]]
array2d[:2,:2]:
 [[ 5 10]
 [25 30]]
array2d[2:,2:]:
 [[55 60]
 [75 80]]


In [7]:
import numpy as np
array3d=np.array([
                   [ [2,4,6],
                     [8,10,12],
                     [14,16,18]],

                   [[20,22,24],
                    [26,28,30],
                    [32,34,36]], 

                    [[38,40,42],
                     [44,46,48],
                     [50,52,54]] 
                     ] )
print('array3d[0:2,1:3,1:3]:\n',array3d[0:2,1:3,1:3])
print('array3d[:,1,:]:\n',array3d[:,1,:])
print('array3d[:,:,1:3]:\n',array3d[:,:,1:3])

array3d[0:2,1:3,1:3]:
 [[[10 12]
  [16 18]]

 [[28 30]
  [34 36]]]
array3d[:,1,:]:
 [[ 8 10 12]
 [26 28 30]
 [44 46 48]]
array3d[:,:,1:3]:
 [[[ 4  6]
  [10 12]
  [16 18]]

 [[22 24]
  [28 30]
  [34 36]]

 [[40 42]
  [46 48]
  [52 54]]]


In [8]:
print("array1d[-5:]:",array1d[-5:])
print("array1d[:-5]:",array1d[:-5])
print('array2d[-2:-2:]:\n',array2d[-2:,-2:])
print("array3d[:,-2:,-2:]:",array3d[:,-2:,-2:])

array1d[-5:]: [ 60  70  80  90 100]
array1d[:-5]: [10 20 30 40 50]
array2d[-2:-2:]:
 [[55 60]
 [75 80]]
array3d[:,-2:,-2:]: [[[10 12]
  [16 18]]

 [[28 30]
  [34 36]]

 [[46 48]
  [52 54]]]


Program 5

In [10]:
import numpy as np
a1=np.array([10,20,30])
a2=np.array([40,50,60])
stacked=np.stack((a1,a2),axis=0)
print("Stack arrays along new axis:")
print(stacked)
hstacked=np.hstack((a1,a2))
print("Horizontal stack:")
print(hstacked)
vstacked=np.vstack((a1,a2))
print("Vertical stack:")
print(vstacked)
dstacked=np.dstack((a1,a2))
print("Depth stack:")
print(dstacked)

Stack arrays along new axis:
[[10 20 30]
 [40 50 60]]
Horizontal stack:
[10 20 30 40 50 60]
Vertical stack:
[[10 20 30]
 [40 50 60]]
Depth stack:
[[[10 40]
  [20 50]
  [30 60]]]


In [ ]:
import numpy as np
a1=np.array([[10,20],[30,40]])
a2=np.array([[50,60],[70,80]])
concataxis0=np.concatenate((a1,a2),axis=0)
print("Concatenate along axis0(columns):")
print(concataxis0)
concataxis1=np.concatenate((a1,a2),axis=1)
print("Concatenate along axis1(rows):")
print(concataxis1)


In [ ]:
import numpy as np
a1=np.array([10,20,30])
a2=np.array([[40],[50],[60]])
result=a1+a2
print("Broadcasting addition:")
print(result)

Program 6

In [ ]:
import pandas as pd
data1={
    'Name':['Virat kohli','Yuvraj singh','MS Dhoni'],
    'Age':[40,39,40],
    'City':['Ranchi','punjab','Delhi']
}
df=pd.DataFrame(data1)
data2={
    'Name':['Rohith sharma','Sachin'],
    'Age':[40,39],
    'City':['Mumbai','Mumbai']
}
df2=pd.DataFrame(data2)

dfconcat=pd.concat([df,df2],ignore_index=True)

dffiltered=dfconcat[dfconcat['Age']>35]

dfconcat['senior']=dfconcat['Age']>=40

print("Original dataframe:")
print(df)
print("\nConcatenated dataframe:")
print(dfconcat)
print("\nfiltered dataframe(Age>35):")  
print(dffiltered)
print("\nDataframe with new 'senior' column:")
print(dfconcat) 


Program 7

In [ ]:
import pandas as pd
import numpy as np
data1={
    'Employee':['A','B','C','D','E'],
    'Department':['HR','Finance','IT',np.nan,'IT'],
    'Salary':[50000,60000,np.nan,80000,45000]
    }
df=pd.DataFrame(data1)
print("Original DataFrame:")
print(df)
dffilled=df.fillna({'Department':'Unknown','Salary':0})
print("\nDataFrame with NaN filled:")
print(dffilled)
dfsorted=dffilled.sort_values(by='Salary',ascending=False)
print("\nDataFrame sorted by 'Salary'(Descending):\n",dfsorted)
dfsorted['Salary']=dfsorted['Salary'].replace(0,np.nan)
dfgrouped=dfsorted.groupby('Department')['Salary'].mean().reset_index()
print("Mean salary for each department:\n",dfgrouped)


Program 8


Reading text files


In [ ]:
import pandas as pd
df=pd.read_csv("textfile.txt")
df

Reading CSV files

In [ ]:
import pandas as pd
dfcsv=pd.read_csv("fifa_data.csv")
dfcsv.head(5)

Reading Excel files

In [ ]:
pip install xlrd

In [ ]:
import pandas as pd
data=pd.read_excel("capbudg.xls")
df=pd.DataFrame(data)
print(df)

Reading JSON files

In [ ]:
import json
data={
    "NAme":"A",
    "Age":40,
    "City":"Tirupati",
    "Haschildren":False,
    "Hobbies":["Reading","Travelling","Swimming"]
}
filename="data.json"
with open(filename,'w')as json_file:
    json.dump(data,json_file,indent=4)
print("JSON file {} created successfully".format(filename))    

In [ ]:
dfjson=pd.read_json("data.json")
print(dfjson)

Program 9


Reading pickle files

In [ ]:
import pickle
class Emp:
    def __init__(self,eno,ename,esal,eaddr):
        self.eno=eno
        self.ename=ename
        self.esal=esal
        self.eaddr=eaddr

    def display(self):
        print("eno:{},ename:{},esal:{},eaddr:{}".format(self.eno,self.ename,self.esal,self.eaddr))

e= Emp(10,"Alice",1000,"TPT")

with open("emp.txt",'wb') as f:
        pickle.dump(e,f)
print("Pickling of employee is completed")
with open ("emp.txt",'rb') as f:
    obj=pickle.load(f)
print("Unpickling of employee is completed")
obj.display()    
                    

Reading image files using PIL

In [ ]:
from PIL import Image 
from IPython.display import display
image=Image.open("ds.jpeg")
display(image)
print("Image format:",image.format)
print("Image size:",image.size)
print("Image mode:",image.mode)

Reading multiple files using Glob 

In [ ]:
import glob
files=glob.glob("*.txt")
print("List of text files:",files)
for file in files:
    with  open (file,"r",encoding='utf-8') as f:
       print(f"Contents of {file}:")
       print(f.read())
      
        
     

Importing data from a database

In [ ]:
import sqlite3
db_path="test.db"
conn=sqlite3.connect(db_path)
cursor=conn.cursor()
cursor.execute("CREATE TABLE IF NOT EXISTS Students(id integer,name text,age integer)")
cursor.execute("Insert into students values(1,'Alice',22)")
cursor.execute("insert into students values(2,'Bob',23)")
conn.commit()
print("Data inserted successfullly")
cursor.execute("select*from students")
rows=cursor.fetchall()
print("Database data:")
for row in rows:
    print(row)
conn.close()    

Program 10

In [ ]:
import requests
from bs4 import BeautifulSoup
url='https://quotes.toscrape.com/'
response=requests.get(url)
soup=BeautifulSoup(response.text,'html.parser')
quotes=soup.find_all('div',class_='quote')
for quote in quotes:
    text=quote.find('span',class_='text').get_text()
    author=quote.find('small',class_='author').get_text()
    tags=[tag.get_text() for tag in quote.find_all('a',class_='tag')]         
    print(f"Quote:{text}")     
    print(f"Author:{author}")          
    print(f"Tags:{','.join(tags)}\n")   

Program 11

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder
data = {
    'Loan_ID': ['LP001002', 'LP001003', 'LP001005', 'LP001006', 'LP001008', 'LP001011', 'LP001013'],
    'Gender': ['Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Female'],
    'Married': ['Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No'],
    'Dependents': [0, 1, 0, 0, 2, 0, 0],
    'Education': ['Graduate', 'Graduate', 'Graduate', 'Not Graduate', 'Graduate', 'Graduate', 'Graduate'],
    'ApplicantIncome': [5849, 4583, 3000, 2583, 6000, 5417, 2333],
    'CoapplicantIncome': [0.0, 1508.0, 0.0, 2358.0, 0.0, 4196.0, 1516.0],
    'LoanAmount': [128, 128, 66, 120, 141, 267, 95],
    'Loan_Amount_Term': [360, 360, 360, 360, 360, 360, 360],
    'Credit_History': [1, 1, 1, 1, 1, 1, 1],
    'Property_Area': ['Urban', 'Rural', 'Urban', 'Urban', 'Urban', 'Urban', 'Rural']
}
df = pd.DataFrame(data)
scaler = MinMaxScaler()
dfscaled = df.copy()

dfscaled[['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount']] = scaler.fit_transform(
    dfscaled[['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount']]
)
print("\nData after Feature Scaling:")
print(dfscaled)


std_scaler = StandardScaler()
dfstandardized = df.copy()
dfstandardized[['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount']] = std_scaler.fit_transform(
    dfstandardized[['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount']]
)
print("\nData after Feature Standardization:")
print(dfstandardized)


labelencoder = LabelEncoder()
dflabelencoded = df.copy()
dflabelencoded['Gender'] = labelencoder.fit_transform(dflabelencoded['Gender'])
dflabelencoded['Married'] = labelencoder.fit_transform(dflabelencoded['Married'])
dflabelencoded['Education'] = labelencoder.fit_transform(dflabelencoded['Education'])
dflabelencoded['Property_Area'] = labelencoder.fit_transform(dflabelencoded['Property_Area'])
print("\nData after Label Encoding:")
print(dflabelencoded)


dfonehotencoded = pd.get_dummies(df, columns=['Gender', 'Married', 'Education', 'Property_Area'])
print("\nData after One Hot Encoding:")
print(dfonehotencoded)

Program 12

Bar graph

In [ ]:
!pip install matplotlib

In [ ]:
import matplotlib.pyplot as plot
students=['A','B','C','D']
marks=[95,90,93,94]
plot.bar(students,marks,color='green')
plot.title("Bar Graph Marks")
plot.xlabel("categories")
plot.ylabel("Values")
plot.show()


pie chart

In [ ]:
sizes=[25,25,30,20]
labels=['A','B','C','D']
plot.pie(sizes,labels=labels,autopct='%.2f%%',startangle=140)
plot.title("pie Chart Example")
plot.show()

Box plot

In [ ]:
#simple box plot
import numpy as np
data=[np.arange(0,50,5)]
plot.boxplot(data,patch_artist=True,tick_labels=['X1'])
plot.title("Box plot Example")
plot.show()

In [ ]:
import numpy as np
data=[np.random.normal(0,std,100)for std in range(1,4)]
plot.boxplot(data,vert=True,patch_artist=True,tick_labels=['X1','X2','X3'])
plot.title("Box plot Example")
plot.show()

Histogram

In [ ]:
data=np.random.randn(1000)
#plot.hist(data,bins=30,color='green',alpha=0.7)
plot.hist(data,bins=30,color='b')
plot.title('Histogram Example')
plot.xlabel('Value')
plot.ylabel('Frequency')
plot.show()

Line chart and subplot

In [ ]:
x=np.linspace(0,10,100)
y1=np.sin(x)
y2=np.cos(x)
fig,axs=plot.subplots(2)
axs[0].plot(x,y1,label='sin(x)')
axs[0].set_title('Sine Wave')
axs[0].legend()
axs[1].plot(x,y2,label='cos(x)')
axs[1].set_title('Cosine Wave')
axs[1].legend()
plot.tight_layout()
plot.show()

Scatter plot

In [ ]:

x=np.random.rand(50)
y=np.random.rand(50)
plot.scatter(x,y,color='red')
plot.title('Scatter plot Example')
plot.xlabel('x-axis')
plot.ylabel('y-axis')
plot.show()

Program 13

In [ ]:
import nltk
nltk.download("punkt")
from nltk.tokenize import word_tokenize
nltk.download("wordnet")
nltk.download("stopwords")
nltk.download("punkt_tab")
text="Hello! How are you doing today?"
tokens=word_tokenize(text)
print(tokens)




Program 13 shortened 

In [ ]:
pip install nltk

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
text="Hello! How are you doing today?"
tokens=word_tokenize(text)
print(tokens)


Program 14 

In [ ]:
import nltk 
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import MultinomialNB 
from sklearn import metrics 
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
import pandas as pd 
 
# Download required NLTK resources 
nltk.download('punkt') 
nltk.download('stopwords') 
 
# Sample text data 
data = { 
    'text': [ 
        'I love programming in Python!', 
        'Python is an amazing language.', 
        'I hate getting errors in my code.', 
        'Machine learning is fascinating.', 
        'Natural Language Processing is part of AI.', 
        'I enjoy solving problems with data.', 
        'My code is working perfectly.', 
        'Data science is the future of technology.'  
 
    ], 
    'label': ['positive', 'positive', 'negative', 'positive', 'positive', 'positive', 'negative', 'positive'] 
} 
 
# Create a DataFrame 
df = pd.DataFrame(data) 
 
# Preprocessing: Tokenize and remove stopwords 
stop_words = set(stopwords.words('english')) 
 
def preprocess_text(text): 
    tokens = word_tokenize(text.lower()) 
    filtered_tokens = [word for word in tokens if word.isalpha() and word not in stop_words] 
    return ' '.join(filtered_tokens) 
 
df['text'] = df['text'].apply(preprocess_text) 
 
# Convert text data to numerical features 
vectorizer = TfidfVectorizer() 
X = vectorizer.fit_transform(df['text']) 
 
# Define target variable 
y = df['label'] 
 
# Split the dataset into training and testing sets 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 
 
# Train a classifier 
model = MultinomialNB() 
model.fit(X_train, y_train) 
 
# Make predictions 
y_pred = model.predict(X_test) 
 
# Evaluate the model 
accuracy = metrics.accuracy_score(y_test, y_pred) 
print(f'Accuracy: {accuracy:.2f}') 
 
# Display classification report 
print(metrics.classification_report(y_test, y_pred)) 

Program 15

In [11]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')


[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\saiva\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.


True

In [12]:
import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag

# Download necessary NLTK packages
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
# Sample text
text = "NLTK is a powerful library for natural language processing in Python."
# Tokenize the text
tokens = word_tokenize(text)
# Part-of-Speech tagging
pos_tags = pos_tag(tokens)

# Display the result
print("Tokens:", tokens)
print("POS Tags:", pos_tags)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\saiva\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\saiva\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


Tokens: ['NLTK', 'is', 'a', 'powerful', 'library', 'for', 'natural', 'language', 'processing', 'in', 'Python', '.']
POS Tags: [('NLTK', 'NNP'), ('is', 'VBZ'), ('a', 'DT'), ('powerful', 'JJ'), ('library', 'NN'), ('for', 'IN'), ('natural', 'JJ'), ('language', 'NN'), ('processing', 'NN'), ('in', 'IN'), ('Python', 'NNP'), ('.', '.')]
